
from .shuffling_vit import ShufflingViTForImageClassification
from .shuffling_deit import ShufflingDeiTForImageClassification

from .position_predicting_vit import PositionPredictingViTForImageClassification
from .position_predicting_deit import PositionPredictingDeiTForImageClassification

from .postition_encoding_vit import PositionEncodingViTForImageClassification
from .postition_encoding_deit import PositionEncodingDeiTForImageClassification
