# Data
DATA:
  DATASET: 'CIFAR-100'
  TRAIN_PATH: 'data/CIFAR-100'
  TEST_PATH: 'data/CIFAR-100'

# Experiment paramters
RANDOM_SEED: 0
NUM_RUNS: 5
GPU_ID: 0
N_WORKERS: 8

# Model to use
MODEL:
  NAME: "ShufflingViTForImageClassification"
  PREPNAME: "ViTImageProcessor"
  CONF: "google/vit-base-patch16-224"
  PRETRAINED: False
  SHUFFLE: True
  IMG_SIZE: 224

# Experiment logging information
EXPERIMENT_LOG:
  BASEPATH: "/dtu/p1/matfre/models/"
  MODEL_NAME: "ShufflingViTForImageClassification"
  EXPERIMENT_NAME: "LayerShuffle-CIFAR100_lr_1e-4_epochs_20"

# optimizer to use
OPTIMIZER:
  EPOCHS: 100
  BATCH_SIZE_TRAIN: 8
  BATCH_SIZE_EVAL: 1600
  LR: 1e-4