# Data
DATA:
  DATASET: "ImageNet2012"
  TRAIN_PATH: "/dtu/datasets1/imagenet_object_localization_patched2019/ILSVRC/Data/CLS-LOC/train/"
  TEST_PATH: "/dtu/p1/matfre/data/imagenet2012/val/"

# Experiment paramters
RANDOM_SEED: 0
NUM_RUNS: 5
GPU_ID: 0
N_WORKERS: 4

# Model to use
MODEL:
  NAME: "PositionPredictingViTForImageClassification"
  PREPNAME: "ViTImageProcessor"
  CONF: "google/vit-base-patch16-224"
  SHUFFLE: True
  IMG_SIZE: 224

# Experiment logging information
EXPERIMENT_LOG:
  BASEPATH: "/dtu/p1/matfre/models/"
  MODEL_NAME: "PositionPredictingViTForImageClassification"
  EXPERIMENT_NAME: "LayerShufflePredict-ImageNet_lr_1e-4_epochs_20"

# optimizer to use
OPTIMIZER:
  EPOCHS: 20
  BATCH_SIZE_TRAIN: 128
  BATCH_SIZE_EVAL: 1600
  LR: 1e-4