# Data
DATA:
  DATASET: 'CIFAR-100'
  TRAIN_PATH: 'data/CIFAR-100'
  TEST_PATH: 'data/CIFAR-100'

# Experiment paramters
RANDOM_SEED: 0
NUM_RUNS: 5
GPU_ID: 0
N_WORKERS: 8

# Model to use
MODEL:
  NAME: "PositionPredictingViTForImageClassification"
  CONF: "google/vit-base-patch16-224"
  SHUFFLE: True

# Experiment logging information
EXPERIMENT_LOG:
  BASEPATH: 'results-reproduced/LiquidTransformers'
  MODEL_NAME: "PositionPredictingViTForImageClassification"
  EXPERIMENT_NAME: f"PositionPredictingViTForImageClassification_lr_1e-4_epochs_1_seed_0"

# optimizer to use
OPTIMIZER:
  EPOCHS: 100
  BATCH_SIZE_TRAIN: 160
  BATCH_SIZE_EVAL: 1600
  LR: 1e-4