# Data
DATA:
  DATASET: 'ImageNet2012'
  TRAIN_PATH: '~/data/imagenet2012/train/'
  TEST_PATH: '~/data/imagenet2012/val/'

# Experiment paramters
RANDOM_SEED: 0
NUM_RUNS: 5
GPU_ID: 0
N_WORKERS: 8

# Model to use
MODEL:
  NAME: "ViTForImageClassification"
  CONF: "google/vit-base-patch16-224"

# Experiment logging information
EXPERIMENT_LOG:
  BASEPATH: 'results-reproduced/LiquidTransformers'
  MODEL_NAME: "ViTForImageClassification"
  EXPERIMENT_NAME: f"ViTForImageClassification_lr_1e-4_epochs_1_seed_0"

# optimizer to use
OPTIMIZER:
  EPOCHS: 1
  BATCH_SIZE_TRAIN: 160
  BATCH_SIZE_EVAL: 1600
  LR: 1e-4