# Data
DATA:
  TRAIN_PATH: '~/data/imagenet2012/train/'
  TEST_PATH: '~/data/imagenet2012/val/'

# Experiment parameters
RANDOM_SEED: 0
NUM_RUNS: 5
GPU_ID: 0
N_WORKERS: 8

# Model to use
MODEL:
  NAME: "ShufflingViTForImageClassification"
  CONF: "google/vit-base-patch16-224"
  SHUFFLE: True

# Experiment logging information
EXPERIMENT_LOG:
  BASEPATH: 'results-reproduced/LiquidTransformers'
  MODEL_NAME: "ShufflingViTForImageClassification"
  EXPERIMENT_NAME: f"ShufflingViTForImageClassification-4_epochs_1_seed_0"

# optimizer to use
OPTIMIZER:
  EPOCHS: 1
  BATCH_SIZE_TRAIN: 160
  BATCH_SIZE_EVAL: 1600
  LR: 1e-4